openapi: 3.0.0
info:
  title: todo
  description: todo app API
  version: 0.1.9

servers:
  - url: https://devjobs-vaqx.onrender.com/api
    description: todo server
  - url: http://localhost:3000/api
    description: local server


paths:
  /job/{size}/{page}:
    get:
      summary: Get a list of jobs with pagination.
      parameters:
        - in: path
          name: size
          schema:
            type: integer
            minimum: 1
            maximum: 100
          required: true
          description: The number of jobs to retrieve per page.
        - in: path
          name: page
          schema:
            type: integer
            minimum: 1
          required: true
          description: The page number of the job list to retrieve.
      responses:
        200:
          description: A list of jobs.
        
